services:
  - type: web
    name: ishowspeed-analytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_server.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: REDIS_HOST
        value: localhost
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_DB
        value: 0